/*
389. Find the Difference

You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.

Example 1:

Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.
Example 2:

Input: s = "", t = "y"
Output: "y"
*/
class Solution {
    public char findTheDifference(String s, String t) {
        //7 bit ascii, 2 to the power 7 equals 128 characters. 
        int[] count = new int[128];
        for(char c: s.toCharArray()) count[c]++;
        for(char c: t.toCharArray()) count[c]--;
        int result = 0;
        for(int i = 0; i<count.length; i++){
            //use condition when char != 0, because + and - operations above should make 
            //everything 0
           if(count[i]!=0){
                 return (char)i;           
           }
       }   
         return '/';       
    }
}